### ISSUE TITLE
planetCenter not found?

### ISSUE THREAD

**Issue by AndrewAnnex** [NASA-AMMOS/LithoSphere#50]
getting the following error when trying to serve and run the demos locally
TypeError: undefined is not a constructor (evaluating 'new three__WEBPACK_IMPORTED_MODULE_4__.SphereBufferGeometry(this.planetCenter.y * 1000, 64, 64)')

**Comment by tariqksoliman** [comment]
Hi! Could you provide some more context. Which branch, what command are you using to run it: `npm start`, `npm run start:dev`, `npm run start:demo`? Have you run `npm install` first? Were there any errors in the terminal?

Also the error above is suggesting that `three__WEBPACK_IMPORTED_MODULE_4__.SphereBufferGeometry` is what's undefined. So maybe three.js didn't get properly imported.

**Comment by AndrewAnnex** [comment]
okay I figured out this was partially due to my bad attempts to update the dependencies due to the report from npm install. I also found some issues with git conflicts being merged into example.html https://github.com/NASA-AMMOS/LithoSphere/blob/0a7f4faea5499c56d2ab02f1e78ce22410ac74e7/public/examples/example.html#L44-L57

```
added 1373 packages, and audited 1374 packages in 8s

12 packages are looking for funding
  run `npm fund` for details

25 vulnerabilities (9 moderate, 12 high, 4 critical)

To address all issues, run:
  npm audit fix
```
